AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.8

  Pumps SQS messages into an RDS database
Globals:
  Function:
    Timeout: 300

Resources:
  SQSToRDSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sqs_to_rds/
      Handler: app.lambda_handler
      Runtime: python3.8
      Tags:
        Project: "rrg-creator"
      VpcConfig:
        SecurityGroupIds:
          - sg-8b5c50ee
        SubnetIds:
          - subnet-6577a03c
          - subnet-a752c0c2
          - subnet-325eee45
      Policies:
        - Statement:
            - Sid: ReadSQS
              Effect: Allow
              Action:
                - sqs:ReceiveMessage
              Resource: arn:aws:sqs:us-west-2:036372598227:quote-updates
      Events:
        SQSToRDS:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:036372598227:quote-updates
            BatchSize: 10
            Enabled: true
